# -*- dockerfile -*-
#
#  Copyright 2018, 2019, 2020 Liang Chen <liangchenomc@gmail.com>
#
#  This file is part of venv-unprivileged-docker.
#
#  venv-unprivileged-docker is free software: you can redistribute it
#  and/or modify it under the terms of the GNU Affero General Public License
#  as published by the Free Software Foundation, either version 3 of
#  the License, or (at your option) any later version.
#
#  venv-unprivileged-docker is distributed in the hope that it will be
#  useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with venv-unprivileged-docker.
#  If not, see <https://www.gnu.org/licenses/>.
#
# dockerfile -- Py3 application image
FROM debian:buster

ENV RUNTIME_BASE=/opt/runtime

ARG BUILD_BASE=/opt/build

ARG PKG_NAME=simple
ARG WITH_NGINX

ARG IMG_UID
ARG IMG_USER
ARG IMG_USER_HOME
ARG IMG_USER_PASS

COPY stage1.sh $BUILD_BASE
COPY $PKG_NAME.deb $BUILD_BASE

RUN bash $BUILD_BASE/stage1.sh
USER $IMG_UID
WORKDIR $IMG_USER_HOME
RUN bash /usr/share/$PKG_NAME/bootstrap.bash

ENTRYPOINT ["/bin/bash", "/opt/runtime/entry-point.sh"]
